version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kinesis-consumer-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1eduxznlzn51t"
s3_prefix = "kinesis-consumer-test"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
